#ifndef pinDef_H
#define pinDef_H


//LEDs
#define CHARGE_FAULT_LED_PORT GPIOA
#define CHARGE_FAULT_LED_PIN GPIO_PIN_15

#define HEARTBEAT_SENSE_LED_PORT GPIOC
#define HEARTBEAT_SENSE_LED_PIN GPIO_PIN_10

#define BPS_SENSE_LED_PORT GPIOC
#define BPS_SENSE_LED_PIN GPIO_PIN_11

#define ELCON_SENSE_LED_PORT GPIOC
#define ELCON_SENSE_LED_PIN GPIO_PIN_12

//Buzzer
#define BUZZER_PORT GPIOB
#define BUZZER_PIN GPIO_PIN_12

//EStop
#define ESTOP_PORT GPIOC
#define ESTOP_PIN GPIO_PIN_3

#endif